- name: Run playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    playbook: add_vlan.yml
    directory: ./
    inventory: |
      [all]
      ${{ secrets.NXOSIP }} 
    options: |
      --extra-vars nxospwd=${{ secrets.NXOSPWD }}
      --verbose
