- name: Run playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    playbook: deploy.yml
    directory: ./
    inventory: |
      [all]
      ${{ secrets.NXOSIP }} 
    options: |
      --extra-vars hello=there
      --verbose
